services:
  - type: web
    name: russell-catways-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        value: "mongodb+srv://russell:LA1UxqlMTgIjhwWC@cluster0.iwoe1fc.mongodb.net/"
      - key: JWT_SECRET
        value: "tonsecretperso"
